# Generated by Django 5.0 on 2024-03-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_auth', '0002_remove_application_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='role',
        ),
    ]
